"""Wellbeing Intelligence V2 (SHADOW) — registry and formula constants."""

from intelligence_maxxxing.domain_packs.life.wellbeing_v2.registry import (
    ACCUMULATION_RETENTION,
    ACUTE_CHRONIC_ANTICIPATORY,
    CALIBRATION_MIN_LABELS,
    COLD_START_MIN_DAYS,
    CONFIDENCE_WEIGHTS,
    DECAYS,
    DOMAIN_CAPS,
    FORMULA_ID,
    FORMULA_STATUS,
    FORMULA_VERSION,
    HAPPINESS_WEIGHTS,
    OVERALL_CONFIDENCE_BLEND,
    STRESS_WEIGHTS,
    TANH_TEMPERATURE,
    WEIGHTS,
)

__all__ = [
    "ACCUMULATION_RETENTION",
    "ACUTE_CHRONIC_ANTICIPATORY",
    "CALIBRATION_MIN_LABELS",
    "COLD_START_MIN_DAYS",
    "CONFIDENCE_WEIGHTS",
    "DECAYS",
    "DOMAIN_CAPS",
    "FORMULA_ID",
    "FORMULA_STATUS",
    "FORMULA_VERSION",
    "HAPPINESS_WEIGHTS",
    "OVERALL_CONFIDENCE_BLEND",
    "STRESS_WEIGHTS",
    "TANH_TEMPERATURE",
    "WEIGHTS",
]
