"""Stable object identity with recommended prefixes (TECHNICAL_ARCHITECTURE.md §8)."""

import uuid
from typing import Final

OBSERVATION_PREFIX: Final = "obs"
EVIDENCE_PREFIX: Final = "evd"
HYPOTHESIS_PREFIX: Final = "hyp"
EXPERIMENT_PREFIX: Final = "exp"
BELIEF_PREFIX: Final = "blf"
RECOMMENDATION_PREFIX: Final = "rec"
DECISION_PREFIX: Final = "dec"
OUTCOME_PREFIX: Final = "out"
LEARNING_PREFIX: Final = "lrn"
AUDIT_PREFIX: Final = "aud"
JOB_PREFIX: Final = "job"
EVENT_PREFIX: Final = "evt"
REQUEST_PREFIX: Final = "req"
SOURCE_PREFIX: Final = "src"
HUMAN_VALUE_PREFIX: Final = "val"


def new_id(prefix: str) -> str:
    """Generate a stable, prefixed, globally unique object ID."""
    return f"{prefix}_{uuid.uuid4().hex}"


def id_pattern(prefix: str) -> str:
    """Regex pattern for validating IDs generated by :func:`new_id`."""
    return rf"^{prefix}_[0-9a-f]{{32}}$"
